import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import ShoppingCartProvider from "./components/Cart/ShoppingCartProvider";
import CartModal from "./components/Cart/CartModal";

const inter = Inter({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
    title: "NextJS Ecommerce",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} min-w-[500px]`}>
                <ShoppingCartProvider>
                    <Nav />
                    <CartModal />
                    {children}
                </ShoppingCartProvider>
            </body>
        </html>
    );
}
